### ISSUE TITLE
Floating footer on Home and Map pages

### ISSUE THREAD

**Issue by atleehlavinka** [robswc/nadocast-ui#38]
When there isn't enough content to fill the screen, the footer floats under wherever the content ends. I think the footer should be fixed to the bottom of the page. I'd love to be assigned this issue and see if I can't fix that.

**Comment by robswc** [comment]
That would be awesome if you could do that!

Let me know if you need anything!

**Comment by atleehlavinka** [comment]
Added the fixed-bottom bootstrap attribute to the footer element. In my testing this fixed the hovering footer issue. Submitted PR #39
